import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
// import TwScreenInfo from "@/components/custom/TwScreenInfo";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans", // Add a CSS variable if you want to use it globally
  weight: ["300", "400", "600", "700", "800"], // Include the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${openSans.variable} antialiased`}
      >
        {children}
        <Analytics />
        <SpeedInsights />
        {/* <TwScreenInfo /> */}
      </body>
    </html>
  );
}
